# GolangCI-Lint Configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  go: '1.22'

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable-all: false

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    # Ignore these functions - they're fire-and-forget
    exclude-functions:
      - (*net/http.ResponseWriter).Write
      - (io.Writer).Write

issues:
  exclude-rules:
    # Ignore test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    # Ignore main.go for some checks
    - path: main\.go
      linters:
        - gochecknoglobals
    # Ignore error checks in certain files (fire-and-forget operations)
    - path: internal/gateway/process\.go
      linters:
        - errcheck
    - path: internal/auth/browser\.go
      linters:
        - errcheck
    - path: internal/cmd/
      linters:
        - errcheck

